### ISSUE TITLE
Add examples of using additional Crashlytics methods

### ISSUE THREAD

**Issue by klm1** [twitterdev/cannonball-ios#3]
Would be great to see more **Crashlytics** examples (over and above initialization) in the code, such as: 

* User Information: `setUserIdentifier`
* Custom Keys: `[Crashlytics setObjectValue:forKey:]`
* Custom Logging: `CLS_LOG`

**Comment by romainhuet** [comment]
Hey @klm1, thank you for the feedback! That’s a great idea, we will definitely provide more examples for these Crashlytics features.

I have some updates coming to Cannonball for iOS shortly. I’ll try to land your suggestions in the project as soon as possible, I’ll keep your ticket open in the meantime.

Thanks!

**Comment by romainhuet** [comment]
I added some examples throughout the project:

- Custom Logging with `CLSLogv`
- Custom Keys with `setObjectValue`
- User Information tied to crash reports with `setUserIdentifier` and `setUserName`

Check out this commit: https://github.com/twitterdev/cannonball-ios/commit/24d89923a17ec7b83decea19bd95432a2e332230

Thanks again @klm1 for the suggestion!

**Comment by klm1** [comment]
Excellent, @romainhuet -- thanks!
